source 'https://rubygems.org'


group :jekyll_plugins do
    gem 'github-pages', "~> 213"
    gem 'jekyll-admin'
    gem 'jekyll-seo-tag'
    gem 'jekyll-gist'
    gem 'jekyll-feed', "~> 0.12"
    gem 'jemoji'
    gem "jekyll-paginate-v2", "~> 2.0"
    gem "html-proofer"
    gem "tzinfo", "~> 1.2"
    gem "tzinfo-data"
end
